---
# tasks file for ansible-graylog
- name: Update and Upgrade
  apt:
    upgrade: yes
    update_cache: yes
    force_apt_get: yes

- name: Install additional packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"

- name: install elasticsearch
  import_tasks: install-elasticsearch.yml

- name: install graylog-server
  import_tasks: install-graylog-server.yml
